# Generated by Django 4.1.5 on 2023-01-29 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='name',
            field=models.CharField(default='message', max_length=50),
            preserve_default=False,
        ),
    ]
