# Generated by Django 4.1.5 on 2023-01-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0002_thread_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='name',
            field=models.CharField(default='message', max_length=50),
        ),
    ]
