# Generated by Django 4.1.5 on 2023-01-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0004_alter_thread_name_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AlterField(
            model_name='player',
            name='chat_id',
            field=models.IntegerField(),
        ),
    ]
