# Generated by Django 4.1.5 on 2023-01-29 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0005_remove_player_name_alter_player_chat_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='next_chapter',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
