# Generated by Django 4.1.5 on 2023-01-29 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0006_player_next_chapter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chapter_on',
            field=models.ForeignKey(default='intro', on_delete=django.db.models.deletion.CASCADE, to='kites_game.thread'),
        ),
    ]
