# Generated by Django 4.1.5 on 2023-01-29 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0007_alter_player_chapter_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='chapter_on',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kites_game.thread'),
        ),
    ]
