# Generated by Django 4.1.5 on 2023-01-31 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kites_game', '0008_alter_player_chapter_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='image',
            field=models.ImageField(blank=True, upload_to='static/images'),
        ),
    ]
